package com.istream.ihr.vo.orm;
// Generated 21-May-2016 13:20:47 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpClientAs generated by hbm2java
 */
@Entity
@Table(name = "emp_client_as", catalog = "ihr")
public class EmpClientAs implements java.io.Serializable {

	private Integer empClientId;
	private Client client;
	private Employee employee;
	private Date startDate;
	private Date endDate;
	private Date creationTs;
	private Date lastUpdateTs;

	public EmpClientAs() {
	}

	public EmpClientAs(Client client, Employee employee, Date startDate, Date creationTs, Date lastUpdateTs) {
		this.client = client;
		this.employee = employee;
		this.startDate = startDate;
		this.creationTs = creationTs;
		this.lastUpdateTs = lastUpdateTs;
	}

	public EmpClientAs(Client client, Employee employee, Date startDate, Date endDate, Date creationTs,
			Date lastUpdateTs) {
		this.client = client;
		this.employee = employee;
		this.startDate = startDate;
		this.endDate = endDate;
		this.creationTs = creationTs;
		this.lastUpdateTs = lastUpdateTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Emp_client_id", unique = true, nullable = false)
	public Integer getEmpClientId() {
		return this.empClientId;
	}

	public void setEmpClientId(Integer empClientId) {
		this.empClientId = empClientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Client_id", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Emp_id", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Start_date", nullable = false, length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "End_date", length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Creation_ts", nullable = false, length = 0)
	public Date getCreationTs() {
		return this.creationTs;
	}

	public void setCreationTs(Date creationTs) {
		this.creationTs = creationTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_update_ts", nullable = false, length = 0)
	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
