package com.istream.ihr.vo.orm;
// Generated 21-May-2016 13:20:47 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpImmigrationDtl generated by hbm2java
 */
@Entity
@Table(name = "emp_immigration_dtl", catalog = "ihr")
public class EmpImmigrationDtl implements java.io.Serializable {

	private Integer empImmDtlId;
	private Employee employee;
	private String immType;
	private Date startDate;
	private Date endDate;
	private Date creationTs;
	private Date lastUpdateTs;

	public EmpImmigrationDtl() {
	}

	public EmpImmigrationDtl(Employee employee, String immType, Date startDate, Date endDate, Date creationTs,
			Date lastUpdateTs) {
		this.employee = employee;
		this.immType = immType;
		this.startDate = startDate;
		this.endDate = endDate;
		this.creationTs = creationTs;
		this.lastUpdateTs = lastUpdateTs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Emp_imm_dtl_id", unique = true, nullable = false)
	public Integer getEmpImmDtlId() {
		return this.empImmDtlId;
	}

	public void setEmpImmDtlId(Integer empImmDtlId) {
		this.empImmDtlId = empImmDtlId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "Imm_type", nullable = false, length = 10)
	public String getImmType() {
		return this.immType;
	}

	public void setImmType(String immType) {
		this.immType = immType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Creation_ts", nullable = false, length = 0)
	public Date getCreationTs() {
		return this.creationTs;
	}

	public void setCreationTs(Date creationTs) {
		this.creationTs = creationTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_update_ts", nullable = false, length = 0)
	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

}
