package com.istream.ihr.vo.orm;
// Generated 21-May-2016 13:20:47 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HealthCarrier generated by hbm2java
 */
@Entity
@Table(name = "health_carrier", catalog = "ihr")
public class HealthCarrier implements java.io.Serializable {

	private Integer carrierId;
	private String name;
	private String address;
	private Date startDate;
	private Date endDate;
	private Date creationTs;
	private Date lastUpdateTs;
	private Set<EmpHealthPlan> empHealthPlans = new HashSet<EmpHealthPlan>(0);

	public HealthCarrier() {
	}

	public HealthCarrier(String name, String address, Date startDate, Date creationTs, Date lastUpdateTs) {
		this.name = name;
		this.address = address;
		this.startDate = startDate;
		this.creationTs = creationTs;
		this.lastUpdateTs = lastUpdateTs;
	}

	public HealthCarrier(String name, String address, Date startDate, Date endDate, Date creationTs, Date lastUpdateTs,
			Set<EmpHealthPlan> empHealthPlans) {
		this.name = name;
		this.address = address;
		this.startDate = startDate;
		this.endDate = endDate;
		this.creationTs = creationTs;
		this.lastUpdateTs = lastUpdateTs;
		this.empHealthPlans = empHealthPlans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "carrier_id", unique = true, nullable = false)
	public Integer getCarrierId() {
		return this.carrierId;
	}

	public void setCarrierId(Integer carrierId) {
		this.carrierId = carrierId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Address", nullable = false, length = 250)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Start_date", nullable = false, length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "End_date", length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Creation_ts", nullable = false, length = 0)
	public Date getCreationTs() {
		return this.creationTs;
	}

	public void setCreationTs(Date creationTs) {
		this.creationTs = creationTs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Last_update_ts", nullable = false, length = 0)
	public Date getLastUpdateTs() {
		return this.lastUpdateTs;
	}

	public void setLastUpdateTs(Date lastUpdateTs) {
		this.lastUpdateTs = lastUpdateTs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "healthCarrier")
	public Set<EmpHealthPlan> getEmpHealthPlans() {
		return this.empHealthPlans;
	}

	public void setEmpHealthPlans(Set<EmpHealthPlan> empHealthPlans) {
		this.empHealthPlans = empHealthPlans;
	}

}
